# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac8884a5213f5d1c692128cc12a9ffcc081bec92a88256473fa4de49eecfb4fe03f2d2216d8488c3926f3c44a78ab91a1f43fd627129f5685900652bc4abf070

test:
  secret_key_base: 6e3b99e689078731e5c08752b9dc4e6066877ff3e49aa8d2bc30af2e47ec6c0c2a4a926422a7aa18ed34bfccf5ea4bc0e5cee30f5f681244c2adaa8f59417bf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
